#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.9.{build}

# branches to build
branches:
  only:
    - master
    - stable


#---------------------------------#
#    environment configuration    #
#---------------------------------#
# Build worker image (VM template)
image: Visual Studio 2015

#---------------------------------#
#       build configuration       #
#---------------------------------#
platform: Any CPU

configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: SoftGene.DependencyInstaller.sln      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal


# scripts to run before build
before_build:
  - nuget restore

before_package:


after_build:


build_script:

