#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.9.{build}

# branches to build
branches:
  only:
    - master
    - stable


#---------------------------------#
#    environment configuration    #
#---------------------------------#
# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: c:\projects\DependenciesInstaller
#---------------------------------#
#       build configuration       #
#---------------------------------#
platform: Any CPU
 
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: src\SoftGene.DependencyInstaller.sln      # path to Visual Studio solution or project
  publish_nuget: true
  # MSBuild verbosity level
  verbosity: minimal

environment:
    COVERALLS_REPO_TOKEN:  
       secure: e3Gb5PW4zsAd4gKsn6oy6qpGnp0omvhP4W48ZPXgi2iKOPgJJVGJ+eOq8Mce13Em
    NUGET_API_KEY:
      secure: UXCaeXvAgATXahpggISzAPqRnjeqMGLTHVKbjEHtko9VM2r2FzFEkUlbfhDkBNyW

# scripts to run before build
before_build:
  - nuget restore src\SoftGene.DependencyInstaller.sln 

before_package:


after_build:


build_script:

test_script:
  - cmd: cd src\SoftGene.DependencyInstaller.Tests
  - cmd: dotnet test
on_finish :
  # any cleanup in here

deploy_script:
  - cmd: cd src\SoftGene.DependencyInstaller
  - cmd: dotnet pack
  - cmd: dotnet nuget push SoftGene.DependencyInstaller.0.9.{build}.nupkg NUGET_API_KEY -s https://api.nuget.org/v3/index.json

notifications:
  # Email
  - provider: Email
    to:
      - arturstylus@gmail.com
      - nktlitvinenko@gmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true
